version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps-dev)"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps-ci)"
