name: Deploy

on:
  workflow_run:
    workflows: 
      - Build
    branches: main
    types: 
      - completed

env:
  REGISTRY_HOSTNAME: gcr.io
  IMAGE_NAME: simulation-ui
  PROJECT_ID: tsmc-ntu-g4

jobs:
  shortsha:
    runs-on: ubuntu-latest
    outputs:
      shortsha: ${{ steps.extract-sha.outputs.shortsha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract short SHA
        id: extract-sha
        run: echo "shortsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  push-image:
    runs-on: ubuntu-latest
    needs: shortsha
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2.1.10
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.4

      - name: Configure Docker client
        run: gcloud auth configure-docker

      - name: Build image
        run: |
          echo "Short SHA: ${{ needs.shortsha.outputs.shortsha }}"
          docker build -t "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE_NAME:${{ needs.shortsha.outputs.shortsha }}" \
                       -t "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE_NAME:latest" \
                       --build-arg VITE_BACKEND_BASE_URL="${{ secrets.VITE_BACKEND_BASE_URL }}" .

      - name: Push image
        run: |
          docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE_NAME:${{ needs.shortsha.outputs.shortsha }}"
          docker push "$REGISTRY_HOSTNAME/$PROJECT_ID/$IMAGE_NAME:latest"
